CRITERIA_HOST = ''
CRITERIA_DATABASE = ''
CRITEIRA_USERNAME = ''
CRITERIA_PASSWORD = ''
CRITERIA_DRIVER = '' # make sure the driver is installed on the server
CRITERIA_PORT  = 

AACT_HOST = ''
AACT_PORT = 
AACT_DATABASE = ''
AACT_USERNAME = ''
AACT_PASSWORD = ''

CSRF_ENABLED = 
SECRET_KEY = ''
